# ~/.config/starship.toml

# Global configuration
add_newline = false
command_timeout = 500
format = """$os$username$hostname$kubernetes$directory$git_branch$git_status\n """

# Success and error symbols
[character]
success_symbol = '[✔](bold green) '
error_symbol = '[✘](bold red) '

# Operating Systems
[os]
format = '[$symbol](bold white) '
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

# User
[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Hostname
[hostname]
ssh_only = false
format = 'on [localhost](bold yellow) '
ssh_symbol = ' '
disabled = false

# Directory
[directory]
truncation_length = 1
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = ' 󰌾 '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Git branch
[git_branch]
symbol = ' '
format = 'via [$symbol$branch]($style)'
truncation_length = 3
truncation_symbol = '…'
style = 'bold green'

# Git status
[git_status]
format = '([ \( $all_status$ahead_behind\)]($style) )'
style = 'bold green'
conflicted = '[ confliced=${count}](red) '
up_to_date = '[󰘽 up-to-date](green) '
untracked = '[󰋗 untracked=${count}](red) '
ahead = ' ahead=${count}'
diverged = ' ahead=${ahead_count}  behind=${behind_count}'
behind = ' behind=${count}'
stashed = '[ stashed=${count}](green) '
modified = '[󰛿 modified=${count}](yellow) '
staged = '[󰐗 staged=${count}](green) '
renamed = '[󱍸 renamed=${count}](yellow) '
deleted = '[󰍶 deleted=${count}](red) '

# Kubernetes
[kubernetes]
format = 'via [󱃾 $context\($namespace\)](bold purple) '
disabled = false

# Language and tools configuration
[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
disabled = false

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "
disabled = false

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "
disabled = false

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[terraform]
symbol = " "
disabled = false

[zig]
symbol = " "

[gradle]
symbol = " "

# Disable unnecessary modules
[vagrant]
disabled = true

[helm]
disabled = true
