# ~/.config/starship.toml

# Global configuration
add_newline = false
command_timeout = 500
format = """$os$username$hostname$kubernetes$directory$git_branch$git_status\n """

# Success and error symbols
[character]
success_symbol = '[✔](bold green) '
error_symbol = '[✘](bold red) '

# Operating Systems
[os]
format = '[$symbol](bold white) '
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'

# User
[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Hostname
[hostname]
ssh_only = false
format = 'on [localhost](bold yellow) '
disabled = false

# Directory
[directory]
truncation_length = 1
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Git branch
[git_branch]
symbol = ' '
format = 'via [$symbol$branch]($style)'
truncation_length = 3
truncation_symbol = '…'
style = 'bold green'

# Git status
[git_status]
format = '([ \( $all_status$ahead_behind\)]($style) )'
style = 'bold green'
conflicted = '[ confliced=${count}](red) '
up_to_date = '[󰘽 up-to-date](green) '
untracked = '[󰋗 untracked=${count}](red) '
ahead = ' ahead=${count}'
diverged = ' ahead=${ahead_count}  behind=${behind_count}'
behind = ' behind=${count}'
stashed = '[ stashed=${count}](green) '
modified = '[󰛿 modified=${count}](yellow) '
staged = '[󰐗 staged=${count}](green) '
renamed = '[󱍸 renamed=${count}](yellow) '
deleted = '[󰍶 deleted=${count}](red) '

# Kubernetes
[kubernetes]
format = 'via [󱃾 $context\($namespace\)](bold purple) '
disabled = false

# Disable unnecessary modules
[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true
